version: 0.2
os: windows
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c release -o 'C:\deployment' -f netcoreapp2.1 -r win-x64
      - pwsh ./Install.ps1
      - echo deployed
artifacts:
  files:
    - C:\deployment\*
