version: 0.2
os: windows
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c release -f netcoreapp2.1 -r win-x64
artifacts:
  files:
    - WebApplication3\bin\Release\netcoreapp2.1\win-x64\publish\*
